from copy import deepcopy
from typing import Any

DEFAULT_PLAN_ORDER = [
    "free_canvas",
    "collaborate_start",
    "collaborate_plus",
    "team_start",
    "team_growth",
    "enterprise",
]

DEFAULT_PLAN_CATALOG: dict[str, dict[str, Any]] = {
    "free_canvas": {
        "annual_price_usd": 0,
        "billing_period": "none",
        "board_limit": 1,
        "group_member_limit": 15,
        "group_workspace_limit": 1,
        "included_credits": 0,
        "metadata": {},
        "monthly_price_usd": 0,
        "name": "Free Canvas",
        "page_limit": 3,
        "plan_family": "free",
        "plan_key": "free_canvas",
        "registration_credits": 50,
        "seat_max": 1,
        "seat_min": 1,
        "seat_range": None,
    },
    "collaborate_start": {
        "annual_price_usd": 15,
        "billing_period": "monthly_or_annual",
        "board_limit": None,
        "group_member_limit": 15,
        "group_workspace_limit": 10,
        "included_credits": 1500,
        "metadata": {},
        "monthly_price_usd": 18,
        "name": "Collaborate Start",
        "page_limit": None,
        "plan_family": "collaborate",
        "plan_key": "collaborate_start",
        "registration_credits": 0,
        "seat_max": 1,
        "seat_min": 1,
        "seat_range": "1+ users",
    },
    "collaborate_plus": {
        "annual_price_usd": 20,
        "billing_period": "monthly_or_annual",
        "board_limit": None,
        "group_member_limit": 15,
        "group_workspace_limit": 20,
        "included_credits": 2000,
        "metadata": {},
        "monthly_price_usd": 25,
        "name": "Collaborate Plus",
        "page_limit": None,
        "plan_family": "collaborate",
        "plan_key": "collaborate_plus",
        "registration_credits": 0,
        "seat_max": 1,
        "seat_min": 1,
        "seat_range": "1+ users",
    },
    "team_start": {
        "annual_price_usd": 20,
        "billing_period": "monthly_or_annual",
        "board_limit": None,
        "group_member_limit": 0,
        "group_workspace_limit": 0,
        "included_credits": 2500,
        "metadata": {},
        "monthly_price_usd": 25,
        "name": "Team Start",
        "page_limit": None,
        "plan_family": "team",
        "plan_key": "team_start",
        "registration_credits": 0,
        "seat_max": 15,
        "seat_min": 1,
        "seat_range": "1-15 seats",
    },
    "team_growth": {
        "annual_price_usd": 40,
        "billing_period": "monthly_or_annual",
        "board_limit": None,
        "group_member_limit": 0,
        "group_workspace_limit": 0,
        "included_credits": 5500,
        "metadata": {},
        "monthly_price_usd": 45,
        "name": "Team Growth",
        "page_limit": None,
        "plan_family": "team",
        "plan_key": "team_growth",
        "registration_credits": 0,
        "seat_max": 15,
        "seat_min": 1,
        "seat_range": "1-15 seats",
    },
    "enterprise": {
        "annual_price_usd": None,
        "billing_period": "contract",
        "board_limit": None,
        "group_member_limit": None,
        "group_workspace_limit": None,
        "included_credits": 0,
        "metadata": {},
        "monthly_price_usd": None,
        "name": "Enterprise",
        "page_limit": None,
        "plan_family": "enterprise",
        "plan_key": "enterprise",
        "registration_credits": 0,
        "seat_max": None,
        "seat_min": None,
        "seat_range": "custom",
    },
}


def copy_default_plan_catalog() -> dict[str, dict[str, Any]]:
    return deepcopy(DEFAULT_PLAN_CATALOG)
